# Generated by Django 5.2.7 on 2025-11-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='screeningquestion',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='applier',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='applier',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
