# Generated by Django 5.2.8 on 2025-11-10 16:14

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appliers', '0003_enable_postgis'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE appliers_applier
                ADD COLUMN location geography(Point, 4326)
                GENERATED ALWAYS AS (
                    ST_SetSRID(
                        ST_MakePoint(
                            longitude::double precision,
                            latitude::double precision
                        ),
                        4326
                    )
                ) STORED;
            """,
            reverse_sql="""
                ALTER TABLE appliers_applier
                DROP COLUMN location;
            """
        ),
    ]
