# Generated by Django 5.2.8 on 2025-11-10 16:14

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appliers', '0003_enable_postgis'),
    ]

    operations = [
        migrations.AddField(
            model_name='applier',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
