# Generated by Django 5.2.8 on 2025-11-10 16:14

from django.db import migrations
from django.contrib.gis.geos import Point


def populate_location_from_lat_lon(apps, schema_editor):
    """
    Populate the location PointField from existing latitude and longitude values.
    """
    Applier = apps.get_model('appliers', 'Applier')
    appliers_query = Applier.objects.filter(
        latitude__isnull=False,
        longitude__isnull=False
    )
    
    appliers_to_update = []
    for applier in appliers_query:
        # Create Point with (longitude, latitude) order - GIS convention
        applier.location = Point(float(applier.longitude), float(applier.latitude), srid=4326)
        appliers_to_update.append(applier)

    # Bulk update for efficiency
    if appliers_to_update:
        Applier.objects.bulk_update(appliers_to_update, ['location'], batch_size=1000)


def reverse_populate(apps, schema_editor):
    """
    Reverse migration: clear the location field.
    """
    Applier = apps.get_model('appliers', 'Applier')
    Applier.objects.update(location=None)


class Migration(migrations.Migration):

    dependencies = [
        ('appliers', '0004_applier_location'),
    ]

    operations = [
        migrations.RunPython(populate_location_from_lat_lon, reverse_populate),
    ]
